apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sentiment-triton
  namespace: triton-demo
spec:
  predictor:
    serviceAccountName: triton-sa
    model:
      modelFormat:
        name: onnx
      runtime: kserve-tritonserver
      storageUri: "s3://kserve-triton-lab-559352513391/triton-repo/sentiment"
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2"
          memory: "2Gi"
